SeguimientoEstudiantil/SeguimientoEstudiantil/Controllers/TipoAccionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;
using SeguimientoEstudiantil.Models;

namespace SeguimientoEstudiantil.Controllers
{
    public class TipoAccionesController : Controller
    {
        // GET: TipoAcciones
        public ActionResult Index()
        {
            Session["Estado"] = 4;
            ModeloTipoAcciones mod = new ModeloTipoAcciones();
            Sto_TipoAccionesNE STA = new Sto_TipoAccionesNE();
            mod.lista = STA.ListarTipoAcciones();
            return View(mod);
        }
        ///////////////////////////////
        #region CREATE TIPO ACCION
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ModeloMaestro mod)
        {
            Sto_TipoAccionesNE STANE = new Sto_TipoAccionesNE();
            int rpta = STANE.CrearTipoAccion(mod.Sto_TipoAcciones.tipoAcciones);
            if(rpta > 0)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion
        ///////////////////////////////
        #region DELETE
        public ActionResult Delete(int id)
        {
            Sto_TipoAccionesNE STANE = new Sto_TipoAccionesNE();
            int rpta = STANE.EliminarTipoAccion(id);
            if(rpta > 0)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion
        //////////////////////////////
        #region ACTUALIZAR
        public ActionResult Update(int id)
        {
            Sto_TipoAccionesNE STANE = new Sto_TipoAccionesNE();
            ModeloMaestro mod = new ModeloMaestro();
            mod.Sto_TipoAcciones.tipoAcciones = STANE.getOne(id);
            return View(mod);
        }
        [HttpPost]
        public ActionResult Update(ModeloMaestro mod)
        {
            Sto_TipoAccionesNE STANE = new Sto_TipoAccionesNE();
            int rpta = STANE.ActualizarTipoAccion(mod.Sto_TipoAcciones.tipoAcciones);
            if(rpta > 0)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion
    }
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAcciones/Create.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro

@{
    ViewBag.Title = "Registro de acciones";
}

<div class="jumbotron">
    <h1>Registro de las acciones</h1>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2>Registrar Nueva Accion</h2>
        </div>
        <div class="panel-body">
            <div class="row form-group">
                <div class="col-md-2">@Html.Label("Accion",new { @class = "control-label" })</div>
                <div class="col-md-10">@Html.TextBoxFor(x=>x.Sto_TipoAcciones.tipoAcciones.Accion1, new { @class = "form-control", })</div>
            </div>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Back to List", "Index",null,new { @class = "btn btn-default" })
            -
            <input type="submit" value="Registrar" class="btn btn-primary" />
        </div>
    </div>

}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAcciones/Index.cshtml
@model SeguimientoEstudiantil.Models.ModeloTipoAcciones
@{
    ViewBag.Title = "Tipos de acciones";
}

@*@Html.ActionLink("Registrar una nueva accion", "Create")*@
<div class="box box-primary">
    <div class="box-header with-border">
        <h2 class="box-title">Listado</h2>
    </div>
    <div class="box-body">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h2>Acciones</h2>
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Accion</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var m in Model.lista)
                        {
                            <tr>
                                <th>@m.ID_Sto_TipoAcciones1</th>
                                <th>@m.Accion1</th>
                                <th>
                                    <a href="@Url.Action("Update", "TipoAcciones", new { @Id = m.ID_Sto_TipoAcciones1 })" class="btn btn-warning">
                                        <i class="fa fa-cog fa-lg"></i>
                                    </a>
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="box-footer">
        @Html.ActionLink("Regresar", "Index", "Home")
    </div>
</div>

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAcciones/Update.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Actualizar Tipo Accion";
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Sto_TipoAcciones.tipoAcciones.ID_Sto_TipoAcciones1)
    <div class="box">
        <div class="box-header with-border">
            <h2 class="box-title">Editar</h2>
        </div>
        <div class="box-body">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2>Editar los tipos de acciones</h2>
                </div>
                <div class="panel-body">
                    <div class="row form-group">
                        <div class="col-md-2">@Html.Label("ID", new { @class = "control-label" })</div>
                        <fieldset disabled>
                            <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_TipoAcciones.tipoAcciones.ID_Sto_TipoAcciones1, new { @class = "form-control", @id = "disabledInput" })</div>
                        </fieldset>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-2">@Html.Label("Accion", new { @class = "control-label" })</div>
                        <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_TipoAcciones.tipoAcciones.Accion1, new { @class = "form-control" })</div>
                    </div>
                </div>                
            </div>
        </div>
        <div class="box-footer">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            -
            <input type="submit" value="Actualizar" class="btn btn-primary" />
        </div>
    </div>
}