SeguimientoEstudiantil/SeguimientoEstudiantil/Controllers/TipoAlertaPreguntasController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using SeguimientoEstudiantil.Models;
using System.Web.Routing;
using System;

namespace SeguimientoEstudiantil.Controllers
{
    public class TipoAlertaPreguntasController : Controller
    {
        /// <summary>
        /// Variables globales para el manejo del id de la pregunta para el registro de la respuesta
        /// </summary>
        #region VARIABLES GLOBALES
        private int ID { get; set; }
        #endregion

        ///////////////////////////////////////////////////////////////////////////////////////////////
        ///////////////////////////////////////////////////////////////////////////////////////////////

        #region CARGA DE FORMA AUTOMATICA TODAS LAS PREGUNTAS REGISTRADAS A LA CARACTERIZACION
        // GET: TipoAlertaPreguntas
        public async Task<ActionResult> Index()
        {
            Session["Estado"] = 6;
            ModeloMaestro mod = new ModeloMaestro();
            Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync("http://localhost:53931/api/FormatoCaracterizacionPreguntas");
            var lista = JsonConvert.DeserializeObject<List<Sto_Formato_Caracterizacion_Preguntas>>(json);
            Session["MyLista"] = lista;
            mod.Sto_TipoAlertas_Preguntas.ListarComboBoxAPI = new SelectList(lista, "CodigoInterno1", "DetallePregunta1");
            mod.Sto_TipoAlertas.ListarTiposAlertasComboBox = new SelectList(STANE.ListarTiposAlertas(), "TipoAlerta1", "Nombre1");
            return View(mod);
        }
        ///////////////////////
        public ActionResult PreguntasApis()
        {
            ModeloMaestro mod = new ModeloMaestro();
            Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
            mod.Sto_TipoAlertas.ListarTiposAlertasComboBox = new SelectList(STANE.ListarTiposAlertas(), "TipoAlerta1", "Nombre1");
            return PartialView(mod);
        }
        #endregion

        #region BUSCA LAS PREGUNTAS QUE SE TIENEN EN EL API
        public async Task<ActionResult> Buscar(string contexto, int id, int val)
        {
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync("http://localhost:53931/api/TraerCaracterizacionRespuestas?cod=" + contexto + "&mod=nose");
            var lista = JsonConvert.DeserializeObject<List<Sto_TraerCaracterizacionRespuestas>>(json);
            CreateR(lista, id, val);
            ViewBag.Envio = lista;
            ViewBag.id = id;
            return PartialView();
        }
        //////////////////////////////////////////////////////////////////////////////////////////
        /*public async Task<ActionResult> Buscar(string contexto, int id,int val)
        {
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync("http://localhost:53931/api/TraerCaracterizacionRespuestas?cod=" + contexto + "&mod=nose");
            var lista = JsonConvert.DeserializeObject<List<Sto_TraerCaracterizacionRespuestas>>(json);
            ViewBag.Envio = lista;
            ViewBag.id = id;
            return PartialView();
        }*/
        //////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////
        public async Task<JsonResult> Buscar3(string contexto)
        {
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync("http://localhost:53931/api/FormatoCaracterizacionPreguntas?id=" + contexto);
            var js = Json(json, JsonRequestBehavior.AllowGet);
            return js;
        }
        #endregion

        #region DETALLES GENERALES DE LAS PREGUNTAS REGISTRADAS Y LAS REPUESTAS REGISTRADAS
        // GET: TipoAlertaPreguntas/Details/5
        public ActionResult DetailsP(int id)
        {
            return View();
        }
        //////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////
        public ActionResult DetailsR(int id)
        {
            return View();
        }
        #endregion

        #region REGISTRA UNA NUEVA PREGUNTA Y LOS VALORES DE LAS RESPUESTAS
        // GET: TipoAlertaPreguntas/Create
        public ActionResult CreateP(string cod, string tipo, string des, int val)
        {
            /*if(cod != null)
            {
                RouteValueDictionary ru = new RouteValueDictionary();
                ru.Add("contexto", cod);
                ru.Add("id", 1);
                if (val == 0)
                {
                    ru.Add("val", 0);
                }
                else
                {
                    ru.Add("val", val);
                }
                return RedirectToAction("Buscar", ru);
            }*/
            int id = Convert.ToInt32(tipo.ToString());
            Sto_TipoAlerta_Pregunta STAP;
            Sto_TipoAlerta_Pregunta_NE STAPNE = new Sto_TipoAlerta_Pregunta_NE();
            STAP = STAPNE.Listar_Pregunta_COD_Preg(cod);
            if (STAP.CodigoPRegunta1 == null)
            {
                STAP = new Sto_TipoAlerta_Pregunta(id, cod, des);
                int rpta = STAPNE.Crear_TipoAlerta_Pregunta(STAP);
                if (rpta > 0)
                {
                    RouteValueDictionary ru = new RouteValueDictionary();
                    ru.Add("contexto", cod);
                    ru.Add("id", rpta);
                    if (val == 0)
                    {
                        ru.Add("val", 0);
                    }
                    else
                    {
                        ru.Add("val", val);
                    }
                    return RedirectToAction("Buscar", ru);
                }
            }
            ViewBag.Error = 0;
            return PartialView();
        }
        //////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////
        public int CreateR(List<Sto_TraerCaracterizacionRespuestas> lista, int id, int val)
        {
            Sto_Pregunta_ValoracionRiesgoRespuesta_NE SPVRNE = new Sto_Pregunta_ValoracionRiesgoRespuesta_NE();
            Sto_Pregunta_ValoracionRiesgoRespuesta SPVR = new Sto_Pregunta_ValoracionRiesgoRespuesta();
            int rpta = 0;
            int l = lista.Count();
            foreach (var m in lista)
            {
                SPVR.Id_TipoAlerta_Pregunta1 = id;
                SPVR.ValorRiesgo1 = val;
                SPVR.Respuesta1 = m.Respuesta;
                SPVR.DescripcionRespuesta1 = m.Detalles;
                rpta = SPVRNE.RegistrarRespuestaPorPregunta(SPVR);
            }
            if (rpta > 0 && rpta == l)
            {
                rpta = 1;
            }
            else
            {
                rpta = 0;
            }
            return rpta;
        }
        //////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////
        public int CreatePreguntaLista(string cod, string aler)
        {
            int rpta = 0;
            int a = Convert.ToInt32(aler.ToString());
            Sto_TipoAlerta_Pregunta_NE STAPNE = new Sto_TipoAlerta_Pregunta_NE();
            if ((cod != null) && (a > 0))
            {
                rpta = 1;
            }
            return rpta;
        } 
        public int DeletePreguntaLista(string cod)
        {
            int rpta = 0;
            Sto_TipoAlerta_Pregunta_NE STAPNE = new Sto_TipoAlerta_Pregunta_NE();
            if (cod != null)
            {
                rpta = 1;
            }
            return rpta;
        }
        #endregion

        #region EDITA LA INFORMACION DE LAS PREGUNTAS REGISTRADAS Y LAS RESPUESTAS
        // GET: TipoAlertaPreguntas/Edit/5
        public ActionResult EditP(int id)
        {
            ModeloMaestro mod = new ModeloMaestro();
            Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
            Sto_TipoAlerta_Pregunta_NE STAPNE = new Sto_TipoAlerta_Pregunta_NE();
            mod.Sto_TipoAlertas.ListarTiposAlertasComboBox = new SelectList(STANE.ListarTiposAlertas(), "TipoAlerta1", "Nombre1");
            mod.Sto_TipoAlertas.ListarTiposAlertasComboBox = new SelectList(STANE.ListarTiposAlertas(), "TipoAlerta1", "Nombre1");
            mod.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta = STAPNE.Listar_Pregunta_ByID(id);
            return PartialView(mod);
        }

        // POST: TipoAlertaPreguntas/Edit/5
        [HttpPost]
        public ActionResult EditP(ModeloMaestro mod)
        {
            try
            {
                Sto_TipoAlerta_Pregunta_NE STAPNE = new Sto_TipoAlerta_Pregunta_NE();

                int rpta = STAPNE.EditarPregunta(mod.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta);

                if (rpta > 0)
                {
                    TempData["Erro"] = 1;
                    return RedirectToAction("Details");
                }
                else
                {
                    ViewBag.Erro = 0;
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

SeguimientoEstudiantil/SeguimientoEstudiantil/Controllers/TiposAlertasController.cs
using SeguimientoEstudiantil.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;

namespace SeguimientoEstudiantil.Controllers
{
    public class TiposAlertasController : Controller
    {

        #region TiposAlertas
        // GET: TiposAlertas
        public ActionResult Index()
        {
            Session["Estado"] = 7;
            ModeloMaestro mod = new ModeloMaestro();
            Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
            mod.Sto_TipoAlertas.listaTipoAlertas = STANE.ListarTiposAlertas();
            TempData["Error"] = 0;
            return View(mod);
        }
        #endregion

        #region TiposAlertas/Create
        public ActionResult Create()
        {
            ViewBag.Error = 0;
            ModeloMaestro mod = new ModeloMaestro();
            Sto_AlertaBase_NE STABNE = new Sto_AlertaBase_NE();
            mod.Sto_AlertasBases.ListaAlertaBaseComboBox = new SelectList(STABNE.ListarAlertasBase(), "AlertaBase", "Nombre");
            return PartialView(mod);
        }
        [HttpPost]
        public ActionResult Create(ModeloMaestro mod)
        {

            try
            {
                Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
                mod.Sto_TipoAlertas.TiposAlertas.AlertaBase = mod.Sto_AlertasBases.AlertaBase.AlertaBase;
                int rpta = STANE.CrearTiposAlertas(mod.Sto_TipoAlertas.TiposAlertas);
                if (rpta > 0) return RedirectToAction("Index");
                ViewBag.Error = 0;
                return View();
            }
            catch(Exception ex)
            {
                ViewBag.Error = 1;
                return View();
            }
        }
        #endregion

        #region TiposAlertas/Edit
        public ActionResult Edit(int id)
        {
            ModeloMaestro mod = new ModeloMaestro();
            Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
            mod.Sto_TipoAlertas.TiposAlertas = STANE.getOne(id);
            ViewBag.Error = 0;
            return View(mod);
        }
        [HttpPost]
        public ActionResult Edit(ModeloMaestro mod)
        {
            try
            {
                Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
                int rpta = STANE.ActualizarTiposAlertas(mod.Sto_TipoAlertas.TiposAlertas);
                if (rpta > 0)
                {
                    ViewBag.Error = 2;
                    return View();
                }
                ViewBag.Error = 0;
                return View();
            }
            catch
            {
                ViewBag.Error = 1;
                return View();
            }
        }
        #endregion

        #region TiposAlertas/Delete
        public ActionResult Delete(int id)
        {
            ModeloMaestro mod = new ModeloMaestro();
            Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
            Sto_AlertaBase_NE STABNE = new Sto_AlertaBase_NE();
            mod.Sto_TipoAlertas.TiposAlertas = STANE.getOne(id);
            mod.Sto_AlertasBases.ListaAlertaBaseComboBox = new SelectList(STABNE.ListarAlertasBase(), "AlertaBase", "Nombre");
            ViewBag.Error = 0;
            return View(mod);
        }

        [HttpPost]
        public ActionResult Delete(ModeloMaestro mod)
        {
            try
            {

                Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
                int rpta = STANE.EliminarTiposAlertas(mod.Sto_TipoAlertas.TiposAlertas.TipoAlerta1);
                if(rpta > 0 )
                {
                    ViewBag.Error = 2;
                    return RedirectToAction("Index");
                }
                ViewBag.Error = 0;
                return View(mod);
            }
            catch
            {
                ViewBag.Error = 1;
                return View();
            }
        }
        #endregion
    }
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlertaPreguntas/CreateP.cshtml
@{
    ViewBag.Title = "CreateP";
    var er = ViewBag.Error;
}
<script>

    window.onload = function () {
        $('#modal-danger').modal('show');
    }

</script>


@{
    if (er == 0)
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Ya se encuentra registrada esa preunta en la base de datos
        </div>
    }
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlertaPreguntas/Delete.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@using System.Linq
@using CapaEntidad
@{
    ViewBag.Title = "Delete";
    var t = (List<Sto_Formato_Caracterizacion_Preguntas>)Session["MyLista"];
    var e = ViewBag.Error;
    Sto_Formato_Caracterizacion_Preguntas detallePregunta = new Sto_Formato_Caracterizacion_Preguntas();
}

<h2>Delete</h2>

@{
    if (e == 0)
    {
        <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Error!!!</strong> No se pudo eliminar la pregunta... :( :( :(
        </div>
    }
    else
    if (e == 2)
    {
        <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Error!!!</strong> No se pudo eliminar la pregunta... :( :( :(
        </div>
    }
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta.Id_TipoAlerta_Preguntas1)
    detallePregunta = t.FirstOrDefault(x => x.CodigoInterno1.Equals(Model.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta.CodigoPRegunta1));
    <div class="box box-danger">
        <div class="box-header with-border">
            <h2 class="box-title">Eliminar</h2>
        </div>
        <div class="box-body">
            <div class="row form-group">
                <div class="col-md-2">
                    @Html.Label("ID", new { @class = "control-label" })
                </div>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta.Id_TipoAlerta_Preguntas1, new { @class = "form-control", disabled = "disabled" })
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-2">
                    @Html.Label("Codigo pregunta",new { @class = "control-label" })
                </div>
                <div class="col-md-10">
                    @Html.TextBoxFor(x=>x.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta.CodigoPRegunta1, new { @class = "form-control" , disabled = "disabled" })
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-2">
                    @Html.Label("Pregunta", new { @class = "control-label" })
                </div>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta.CodigoPRegunta1,detallePregunta != null ? detallePregunta.DetallePregunta1 : string.Empty, new { @class = "form-control", disabled = "disabled" })
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-2">
                    @Html.Label("Tipo Alerta", new { @class = "control-label" })
                </div>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta.TipoAlerta1, Model.Sto_TipoAlertas.NombreTipoAlerta(Model.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta.TipoAlerta1), new { @class = "form-control", disabled = "disabled" })
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-2">
                    @Html.Label("Descripcion", new { @class = "control-label" })
                </div>
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Sto_TipoAlertas_Preguntas.TipoAlerta_Pregunta.DescripcionPRegunta1, new { @class = "form-control", disabled = "disabled" })
                </div>
            </div>
        </div>
        <div class="box-footer">
            <input type="submit" value="Eliminar" class="btn btn-danger"/>
            -
            @Html.ActionLink("Regresar", "Details", "TipoAlertaPreguntas",null,new { @class = "btn btn-default" })
        </div>
    </div>
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlertaPreguntas/Details.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@using System.Linq
@using CapaEntidad
@{
    ViewBag.Title = "Details";
    var t = (List<Sto_Formato_Caracterizacion_Preguntas>)Session["MyLista"];
    var i = t.Count;
    var er = Convert.ToInt32(TempData["Error"]);
    var e = Convert.ToInt32(TempData["Erro"]);
}

<script>
    window.onload = function () {
        $('#tablesorter').DataTable();
        AOS.init({
            offset: 200,
            duration: 1000,
            easing: 'ease-out-back',
            delay: 100,
        });        
    }


    function editP(id) {
        $('#myModal').modal("show");
        $("#edit").html("<p><i class='fa fa-spinner fa-3x fa-spin'></i> &nbsp; Carcagndo...</p> ").load('@Url.Action("EditP")/' + id);        
    }

</script>
@{
    if (er == 1)
    {
        <div class="alert alert-success alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Exitoo!!!</strong> Pregunta eliminada correctamente
        </div>
    }
    if (e == 1)
    {
        <div class="alert alert-success alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Exitoo!!!</strong> Configuracion realizada.
        </div>
    }
}
<div class="alert alert-info alert-dismissable">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Info!</strong> Puede consultar las diferentes preguntas y modificar sus valores o eliminarla
</div>

<div class="box box-primary" data-aos="fade-left" data-aos-anchor="selector" data-aos-once="true">
    <div class="box-header with-border">
        <h2 class="box-title">Detalles de la pregunta</h2>
    </div>
    <div class="box-body">

        <table class="table table-bordered table-responsive" id="tablesorter" data-page-length='5'>
            <thead>
                <tr>
                    <th>Id Pregunta</th>
                    <th>Codigo Pregunta</th>
                    <th>Pregunta</th>
                    <th>Tipo Alerta</th>
                    <th>Descripcion</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model.Sto_TipoAlertas_Preguntas.listarTipoAlerta_Pregunta)
                {
                    Sto_Formato_Caracterizacion_Preguntas detallePregunta = new Sto_Formato_Caracterizacion_Preguntas();
                    detallePregunta = t.FirstOrDefault(x => x.CodigoInterno1.Equals(m.CodigoPRegunta1));
                    <tr>
                        <th>@m.Id_TipoAlerta_Preguntas1</th>
                        <th>@m.CodigoPRegunta1</th>
                        <th>@(detallePregunta != null ? detallePregunta.DetallePregunta1 : string.Empty)</th>
                        <th>@m.TipoAlerta1</th>
                        <th>@m.DescripcionPRegunta1</th>
                        <th>
                            <a href="javascript:" onclick="editP(@m.Id_TipoAlerta_Preguntas1);" class="btn btn-warning">
                                <i class="fa fa-cog fa-lg fa-spin"></i>
                            </a>
                            -
                            <a href="@Url.Action("Delete", "TipoAlertaPreguntas",new { @Id = m.Id_TipoAlerta_Preguntas1 })" class="btn btn-danger">
                                <i class="fa fa-trash fa-lg fa-spin"></i>
                            </a>
                        </th>
                    </tr>
                }
            </tbody>
        </table>

    </div>
    <div class="box-footer">
    </div>
</div>

<div id="vista-parcial"></div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Editar</h4>
            </div>
            <div class="modal-body">
                <div id="edit"></div>
            </div>
        </div>
    </div>
</div>

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlertaPreguntas/EditR.cshtml
@{
    ViewBag.Title = "EditR";
}

<h2>EditR</h2>

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlertaPreguntas/ListRespuesta.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Respuestas";
    var er = ViewBag.Error;
}
<script>
    $(document).ready(function () {
        $('#tablesorter').DataTable();
        AOS.init({
            offset: 200,
            duration: 1000,
            easing: 'ease-out-back',
            delay: 100,
        });
    });
</script>


@{
    if (er > 0)
    {
        <div class="alert alert-info" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Para la eliminacion de las respuesta hay que eliminar la pregunta como tal
        </div>
        <div class="box box-primary" data-aos="fade-left" data-aos-anchor="selector" data-aos-once="true">
            <div class="box-header with-border">
                <h2 class="box-title">Listado</h2>
            </div>
            <div class="box-body">
                <table class="table table-bordered table-responsive" id="tablesorter">
                    <thead>
                        <tr>
                            <th>Id Respuesta</th>
                            <th>Pregunta relacionada</th>
                            <th>Cod Respesta</th>
                            <th>Respuesta</th>
                            <th>Valor Riesgo</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var m in Model.Sto_Respuestas.listaRespuestas)
                {
                            <tr>
                                <th>@m.Id_Pregunta_Valoracion1</th>
                                <th>@m.Id_TipoAlerta_Pregunta1</th>
                                <th>@m.Respuesta1</th>
                                <th>@m.DescripcionRespuesta1</th>
                                <th>@m.ValorRiesgo1</th>
                                <th>
                                    <a href="@Url.Action("Edit", "TiposAlertas", new { @Id = m.Id_Pregunta_Valoracion1 })" class="btn btn-default">
                                        <i class="fa fa-cog fa-lg fa-spin"></i>
                                    </a>
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="box-footer">
            </div>
        </div>
    }
    else if (er == 0)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            No se encuentran las respuestas, verifique si la pregunta esta registrada.
        </div>
    }
    else if (er < 0)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            Error en la consulta a la base de datos, intentar des pues.
        </div>
    }
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlertaPreguntas/Respuestas.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Respuestas";
}
<script>
    $(document).ready(function () {
        $('#tablesorter').DataTable();
        AOS.init({
            offset: 200,
            duration: 1000,
            easing: 'ease-out-back',
            delay: 100,
        });
</script>

<div class="alert alert-info" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    Para la eliminacion de las respuesta hay que eliminar la pregunta como tal
</div>

<div class="box box-primary" data-aos="fade-left" data-aos-anchor="selector" data-aos-once="true">
    <div class="box-header with-border">
        <h2 class="box-title">Listado</h2>
    </div>
    <div class="box-body">
        <table class="table table-bordered" id="tablesorter">
            <thead>
                <tr>
                    <th>Id Respuesta</th>
                    <th>Pregunta relacionada</th>
                    <th>Cod Respesta</th>
                    <th>Respuesta</th>
                    <th>Valor Riesgo</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var m in Model.Sto_Respuestas.listaRespuestas)
                {
                    <tr>
                        <th>@m.Id_Pregunta_Valoracion1</th>
                        <th>@m.Id_TipoAlerta_Pregunta1</th>
                        <th>@m.Respuesta1</th>
                        <th>@m.DescripcionRespuesta1</th>
                        <th>@m.ValorRiesgo1</th>
                        <th>
                            <a href="@Url.Action("Edit", "TiposAlertas", new { @Id = m.Id_Pregunta_Valoracion1 })" class="btn btn-default">
                                <i class="fa fa-cog fa-lg fa-spin"></i>
                            </a>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="box-footer">
    </div>
</div>