SeguimientoEstudiantil/SeguimientoEstudiantil/Controllers/NivelRiesgoAlertaController.cs
using SeguimientoEstudiantil.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaNegocio;

namespace SeguimientoEstudiantil.Controllers
{
    public class NivelRiesgoAlertaController : Controller
    {
        #region NivelRiesgoAlerta
        // GET: NivelRiesgoAlerta
        public ActionResult Index()
        {
            Session["Estado"] = 3;
            ModeloMaestro mod = new ModeloMaestro();
            Sto_NivelRiesgoAlerta_NE SNRANE = new Sto_NivelRiesgoAlerta_NE();
            mod.Sto_NivelRiesgoAlerta.listaNivelRiesgoAlerta = SNRANE.ListarNivelRiesgoAlerta();
            return View(mod);
        }
        #endregion 

        #region NivelRiesgoAlerta/Details
        // GET: NivelRiesgoAlerta/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        #endregion

        #region NivelRiesgoAlerta/Create
        // GET: NivelRiesgoAlerta/Create
        public ActionResult Create()
        {
            ViewBag.Error = "si";
            return PartialView();
        }

        // POST: NivelRiesgoAlerta/Create
        [HttpPost]
        public ActionResult Create(ModeloMaestro mod)
        {
            try
            {
                Sto_NivelRiesgoAlerta_NE SNRANE = new Sto_NivelRiesgoAlerta_NE();
                int rpta = SNRANE.CrearNivelRiesgoAlerta(mod.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta);
                if( rpta > 0) return RedirectToAction("Index");
                ViewBag.Error = "no";
                return View();
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region NivelRiesgoAlerta/Edit/
        // GET: NivelRiesgoAlerta/Edit/5
        public ActionResult Edit(int id)
        {
            ModeloMaestro mod = new ModeloMaestro();
            Sto_NivelRiesgoAlerta_NE SNRANE = new Sto_NivelRiesgoAlerta_NE();
            mod.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta = SNRANE.getOneNivelRiesgoAlerta(id);
            ViewBag.Error = 0;
            return View(mod);
        }

        // POST: NivelRiesgoAlerta/Edit/5
        [HttpPost]
        public ActionResult Edit(ModeloMaestro mod)
        {
            try
            {
                // TODO: Add update logic here
                Sto_NivelRiesgoAlerta_NE SNERANE = new Sto_NivelRiesgoAlerta_NE();
                int rpta = SNERANE.ActualizarRiesgoNivelAlerta(mod.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta);
                if (rpta > 0) return RedirectToAction("Index");
                ViewBag.Error = 1;
                return View();
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region NivelRiesgoAlerta/Delete/
        // GET: NivelRiesgoAlerta/Delete/5
        public ActionResult Delete(int id)
        {
            ModeloMaestro mod = new ModeloMaestro();
            Sto_NivelRiesgoAlerta_NE SNRANE = new Sto_NivelRiesgoAlerta_NE();
            mod.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta = SNRANE.getOneNivelRiesgoAlerta(id);
            ViewBag.Error = 0;
            return View(mod);
        }

        // POST: NivelRiesgoAlerta/Delete/5
        [HttpPost]
        public ActionResult Delete(ModeloMaestro mod)
        {
            try
            {
                // TODO: Add delete logic here
                Sto_NivelRiesgoAlerta_NE SNRANE = new Sto_NivelRiesgoAlerta_NE();
                int rpta = SNRANE.EliminarRiesgoNivelAlerta(mod.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.NivelRiesgoAlerta1);
                if( rpta > 0) return RedirectToAction("Index");
                ViewBag.Error = 1;
                return View();
            }
            catch
            {
                ViewBag.Error = 1;
                return View();
            }
        }
        #endregion
    }
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/NivelRiesgoAlerta/Create.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Create";
    var info = ViewBag.Error;
}

@if (info == "no")
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        Error al registrar un nuevo nivel de riesgo
    </div>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="box">
        <div class="box-header with-border">
            <h2 class="box-title">Nuevo Registo</h2>
        </div>
        <div class="box-body">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2>Registro de nuevo nivel de riesgo</h2>
                </div>
                <div class="panel-body">
                    <div class="row form-group">
                        <div class="col-md-2">@Html.Label("Nivel Riesgo Alerta", new { @class = "control-label" })</div>
                        <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.Nombre1, new { @class = "form-control", })</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <input type="submit" value="Registrar" class="btn btn-primary" />
        </div>
    </div>

}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/NivelRiesgoAlerta/Delete.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Delete";

}
@{
    var info = ViewBag.Error;
}
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.NivelRiesgoAlerta1)
    <div class="box box-danger">
        <div class="box-header with-border">
            <h2 class="box-title">Eliminar</h2>
        </div>
        <div class="box-body">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2>Seguro de realizar la eliminación????</h2>
                </div>
                <div class="panel-body">
                    <div class="row form-group">
                        @{
                            if (info > 0)
                            {
                                <div class="alert alert-danger" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    Error al registrar un nuevo nivel de riesgo
                                </div>
                            }
                        }
                        <div class="col-md-2">@Html.Label("Id Nivel Riesgo Alerta", new { @class = "control-label" })</div>
                        <fieldset disabled>
                            <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.NivelRiesgoAlerta1, new { @class = "form-control", })</div>
                        </fieldset>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-2">@Html.Label("Nivel Riesgo Alerta", new { @class = "control-label" })</div>
                        <fieldset disabled>
                            <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.Nombre1, new { @class = "form-control", })</div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            -
            <input type="submit" value="Eliminar" class="btn btn-danger" />
        </div>
    </div>

                            }

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/NivelRiesgoAlerta/Edit.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{

    ViewBag.Title = "Edit";

    var info = ViewBag.Error;

}

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.NivelRiesgoAlerta1)
    <div class="box">
        <div class="box-header with-border">
            <h2 class="box-title">Editar</h2>
        </div>
        <div class="box-body">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2>Editar un registro</h2>
                </div>
                <div class="panel-body">
                    <div class="row form-group">
                        <div class="col-md-2">@Html.Label("Id Nivel Riesgo Alerta", new { @class = "control-label" })</div>
                        <fieldset disabled>
                            <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.NivelRiesgoAlerta1, new { @class = "form-control", })</div>
                        </fieldset>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-2">@Html.Label("Nivel Riesgo Alerta", new { @class = "control-label" })</div>
                        <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.Nombre1, new { @class = "form-control", })</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            -
            <input type="submit" value="Registrar" class="btn btn-primary" />
        </div>
    </div>
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/NivelRiesgoAlerta/Index.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Nivel Riesgo";
}
<script>
    window.onload = function () {
        $("#vista-parcial").html("Cargando...").load('@Url.Action("Create")');
        $('#tabla-nivel').DataTable();
        AOS.init({
            offset: 200,
            duration: 1000,
            easing: 'ease-out-back',
            delay: 100,
        });
    }

</script>
<script>

    hljs.initHighlightingOnLoad();

    $('.hero__scroll').on('click', function (e) {
        $('html, body').animate({
            scrollTop: $(window).height()
        }, 1200);
    });

</script>
<div class="" id="vista-parcial" data-aos="fade-left" data-aos-anchor="selector" data-aos-once="true"></div>
<div class="box box-primary" data-aos="fade-left" data-aos-anchor="selector" data-aos-once="true">
    <div class="box-header with-border">
        <h2 class="box-title">Listado</h2>
        <div class="box-tools pull-right">
            <!-- Buttons, labels, and many other things can be placed here! -->
            <!-- Here is a label for example -->
        </div>
    </div>
    <div class="box-body">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h2>Lista de los niveles de riesgo de las alertas</h2>
            </div>
            <div class="panel-body">
                <table class="table table-bordered" id="tabla-nivel">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nivel Riesgo Alerta</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var m in Model.Sto_NivelRiesgoAlerta.listaNivelRiesgoAlerta)
                        {
                            <tr>
                                <th>@m.NivelRiesgoAlerta1</th>
                                <th>@m.Nombre1</th>
                                <th>
                                    <a href="@Url.Action("Edit", "NivelRiesgoAlerta", new { @Id = m.NivelRiesgoAlerta1 })" class="btn btn-warning">
                                        <i class="fa fa-cog fa-lg"></i>
                                    </a>
                                    -
                                    <a href="@Url.Action("Delete", "NivelRiesgoAlerta", new { @Id = m.NivelRiesgoAlerta1 })" class="btn btn-danger">
                                        <i class="fa fa-trash fa-lg"></i>
                                    </a>
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <div class="box-footer">
        @Html.ActionLink("Regresar", "Index", "Home")
    </div>
</div>