SeguimientoEstudiantil/SeguimientoEstudiantil/Controllers/TipoAlerta_NivelRiesgoController.cs
using SeguimientoEstudiantil.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaNegocio;

namespace SeguimientoEstudiantil.Controllers
{
    public class TipoAlerta_NivelRiesgoController : Controller
    {
        #region TipoAlerta_NivelRiesgo
        // GET: TipoAlerta_NivelRiesgo
        public ActionResult Index()
        {
            Session["Estado"] = 5;
            ModeloMaestro mod = new ModeloMaestro();
            Sto_TipoAlerta_NivelRiesgo_NE STANRNE = new Sto_TipoAlerta_NivelRiesgo_NE();
            mod.Sto_TipoAlerta_NivelRiesgo.ListaTipoAlerta_NivelRiesgo = STANRNE.ListaTipoAlerta_NivelRiesgo();
            return View(mod);
        }
        #endregion

        #region TipoAlerta_NivelRiesgo/Create
        public ActionResult Create()
        {
            Sto_TipoAccionesNE TipoAcciones = new Sto_TipoAccionesNE();
            Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
            Sto_NivelRiesgoAlerta_NE SNRANE = new Sto_NivelRiesgoAlerta_NE();
            ModeloMaestro mod = new ModeloMaestro();
            mod.Sto_NivelRiesgoAlerta.ListaNivelRiesgoAlertaComboBox = new SelectList(SNRANE.ListarNivelRiesgoAlerta(), "NivelRiesgoAlerta1", "Nombre1");
            mod.Sto_TipoAlertas.ListarTiposAlertasComboBox = new SelectList(STANE.ListarTiposAlertas(),  "TipoAlerta1","Nombre1");
            mod.Sto_TipoAcciones.ListarTipoAccionesComboBox = new SelectList(TipoAcciones.ListarTipoAcciones(),  "ID_Sto_TipoAcciones1", "Accion1");
            return PartialView(mod);
        }
        [HttpPost]
        public ActionResult Create(ModeloMaestro mod)
        {
            Sto_TipoAlerta_NivelRiesgo_NE STANRNE = new Sto_TipoAlerta_NivelRiesgo_NE();

            Sto_Accion_TipoAlerta_NivelRiesgo_NE SATANRNE = new Sto_Accion_TipoAlerta_NivelRiesgo_NE();

            mod.Sto_TipoAlerta_NivelRiesgo.
                TipoAlerta_NivelRiesgo.TipoAlerta1 = mod.Sto_TipoAlertas.TiposAlertas.TipoAlerta1;

            mod.Sto_TipoAlerta_NivelRiesgo.
                TipoAlerta_NivelRiesgo.NivelRiesgoAlerta1 = mod.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.NivelRiesgoAlerta1;

            int rpta = STANRNE.CrearTipoAlerta_NivelRiesgo(mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo);

            if (rpta > 0)
            {
                int ultimo = rpta;

                mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.ID_Accion1 =
                    mod.Sto_TipoAcciones.tipoAcciones.ID_Sto_TipoAcciones1;

                mod.Sto_Accion_TipoAlerta_NivelRiesgo.
                    Accion_TipoAlerta.ID_TipoAlerta_NivelRiesgo1 = ultimo;

                int id = mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.ID_Accion1;

                if (id > 0)
                {
                    rpta = SATANRNE.CrearAccion_TipoAlerta_NivelRiesgo(mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta);
                    if (rpta > 0)
                    {
                        return RedirectToAction("Index");
                    }
                }else
                {
                    return RedirectToAction("Index");
                }

            }
            return View();
        }
        #endregion

        #region TipoAlerta_NivelRiesgo/Edit
        public ActionResult Edit(int id)
        {
            Sto_TipoAlerta_NivelRiesgo_NE STANRNE = new Sto_TipoAlerta_NivelRiesgo_NE();
            Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
            Sto_Accion_TipoAlerta_NivelRiesgo_NE SATANRNE = new Sto_Accion_TipoAlerta_NivelRiesgo_NE();
            Sto_NivelRiesgoAlerta_NE SNRANE = new Sto_NivelRiesgoAlerta_NE();
            Sto_TipoAccionesNE STA_NE = new Sto_TipoAccionesNE();
            ModeloMaestro mod = new ModeloMaestro();

            mod.Sto_NivelRiesgoAlerta.
                ListaNivelRiesgoAlertaComboBox = new SelectList(SNRANE.ListarNivelRiesgoAlerta(), "NivelRiesgoAlerta1", "Nombre1");

            mod.Sto_TipoAlertas.
                ListarTiposAlertasComboBox = new SelectList(STANE.ListarTiposAlertas(), "TipoAlerta1", "Nombre1");

            mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo = STANRNE.getOne(id);

            mod.Sto_TipoAcciones.ListarTipoAccionesComboBox = new SelectList(STA_NE.ListarTipoAcciones(), "ID_Sto_TipoAcciones1", "Accion1");

            mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta = SATANRNE.getOne(mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Id_tipoAlerta_NivelRiesgo1);

            mod.Sto_TipoAcciones.tipoAcciones = STA_NE.getOne(mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.ID_Accion1);

            return View(mod);
        }
        [HttpPost]
        public ActionResult Edit(ModeloMaestro mod)
        {
            Sto_TipoAlerta_NivelRiesgo_NE STANRNE = new Sto_TipoAlerta_NivelRiesgo_NE();
            Sto_Accion_TipoAlerta_NivelRiesgo_NE SATANRNE = new Sto_Accion_TipoAlerta_NivelRiesgo_NE();
            /*mod.Sto_TipoAlerta_NivelRiesgo.
               TipoAlerta_NivelRiesgo.TipoAlerta1 = mod.Sto_TipoAlertas.TiposAlertas.TipoAlerta1;

            mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.
                NivelRiesgoAlerta1 = mod.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.NivelRiesgoAlerta1;*/

            int rpta = STANRNE.ActualizarTipoAlerta_NivelRiesgo(mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo);

            if (rpta > 0)
            {

                int i = mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.ID_Accion_TipoAlerta_NivelRiesgo1;
                rpta = 0;
                if (i <= 0)
                {
                    mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.ID_Accion1 = mod.Sto_TipoAcciones.tipoAcciones.ID_Sto_TipoAcciones1;
                    mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.ID_TipoAlerta_NivelRiesgo1 = mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Id_tipoAlerta_NivelRiesgo1;
                    rpta = SATANRNE.CrearAccion_TipoAlerta_NivelRiesgo(mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta);
                    if (rpta > 0)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return View();
                    }
                }

                rpta = SATANRNE.Actualizar(mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta);

                if (rpta > 0)
                {
                    return RedirectToAction("Index");
                }else
                {
                    return View();
                }
            }
            return View();
        }
        #endregion

        #region TipoAlerta_NivelRiesgo/Delete
        public ActionResult Delete(int id)
        {
            ModeloMaestro mod = new ModeloMaestro();
            Sto_TipoAlerta_NivelRiesgo_NE STANRNE = new Sto_TipoAlerta_NivelRiesgo_NE();
            mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo = STANRNE.getOne(id);
            return View(mod);
        }
        [HttpPost]
        public ActionResult Delete(ModeloMaestro mod)
        {
            Sto_TipoAlerta_NivelRiesgo_NE STANRNE = new Sto_TipoAlerta_NivelRiesgo_NE();
            int rpta = STANRNE.EliminarTipoAlerta_NivelRiesgo(mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Id_tipoAlerta_NivelRiesgo1);
            if(rpta > 0)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        public ActionResult Detail(int id)
        {
            Sto_TipoAlerta_NivelRiesgo_NE STANRNE = new Sto_TipoAlerta_NivelRiesgo_NE();
            Sto_TiposAlertas_NE STANE = new Sto_TiposAlertas_NE();
            Sto_Accion_TipoAlerta_NivelRiesgo_NE SATANRNE = new Sto_Accion_TipoAlerta_NivelRiesgo_NE();
            Sto_NivelRiesgoAlerta_NE SNRANE = new Sto_NivelRiesgoAlerta_NE();
            Sto_TipoAccionesNE STA_NE = new Sto_TipoAccionesNE();
            ModeloMaestro mod = new ModeloMaestro();
            mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo = STANRNE.getOne(id);
            mod.Sto_TipoAlertas.TiposAlertas = STANE.getOne(mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.TipoAlerta1);
            mod.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta = SNRANE.getOneNivelRiesgoAlerta(mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.NivelRiesgoAlerta1);
            mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta = SATANRNE.getOne(mod.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Id_tipoAlerta_NivelRiesgo1);
            mod.Sto_TipoAcciones.tipoAcciones = STA_NE.getOne(mod.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.ID_Accion1);
            return View(mod);
        }
    }
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlerta_NivelRiesgo/Create.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Create</h2>
        </div>
        <div class="box-body">
            <div class="contenedor" id="contenedor">
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Tipos Alertas", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.DropDownListFor(x => x.Sto_TipoAlertas.TiposAlertas.TipoAlerta1, Model.Sto_TipoAlertas.ListarTiposAlertasComboBox, "Todos", new { @class = "form-control" })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Puntaje Minimo", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Min_Puntaje1, new { @class = "form-control", })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Puntaje Maximo", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Max_Puntaje1, new { @class = "form-control", })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Nivel Riesgo Alerta", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.DropDownListFor(x => x.Sto_NivelRiesgoAlerta.NivelRiesgoAlerta.NivelRiesgoAlerta1, Model.Sto_NivelRiesgoAlerta.ListaNivelRiesgoAlertaComboBox, "Todos", new { @class = "form-control" })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Accion a realizar", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.DropDownListFor(x => x.Sto_TipoAcciones.tipoAcciones.ID_Sto_TipoAcciones1, Model.Sto_TipoAcciones.ListarTipoAccionesComboBox, "-Todos-", new { @class = "form-control" })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Referencias", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.Referencias1, new { @class = "form-control" })</div>
                </div>
            </div>

        </div>
        <div class="box-footer">
            <input type="submit" value="Registrar" class="btn btn-primary" />
        </div>
    </div>
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlerta_NivelRiesgo/Delete.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Delete";
    var info = ViewBag.Error;

}
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Id_tipoAlerta_NivelRiesgo1)
    <div class="box box-danger">
        <div class="box-header with-border">
            <h2 class="box-title">Delete</h2>
        </div>
        <div class="box-body">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2>Seguro de realizar la eliminación????</h2>
                </div>
                <div class="panel-body">
                    <div class="row form-group">
                        @{
                            if (info > 0)
                            {
                                <div class="alert alert-danger" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    Error al registrar un nuevo nivel de riesgo
                                </div>
                            }
                        }
                        <div class="col-md-2">@Html.Label("ID Regla Alerta", new { @class = "control-label" })</div>
                        <fieldset disabled>
                            <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Id_tipoAlerta_NivelRiesgo1, new { @class = "form-control", })</div>
                        </fieldset>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-2">@Html.Label("Tipo Alerta", new { @class = "control-label" })</div>
                        <fieldset disabled>
                            <div class="col-md-10">@Html.Label(Model.Sto_TipoAlertas.NombreTipoAlerta(Model.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.TipoAlerta1), new { @class = "control-label" })</div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            -
            <input type="submit" value="Eliminar" class="btn btn-danger" />
        </div>
    </div>
                            }
@*
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h2>Seguro de realizar la eliminación????</h2>
        </div>
        <div class="panel-body">

        </div>
        <div class="panel-footer">

        </div>
    </div>
                    }*@

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlerta_NivelRiesgo/Detail.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Detail";
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Id_tipoAlerta_NivelRiesgo1)
    <div class="box box-primary">
        <div class="box-header with-border">
            <h1 class="box-title">Detalles</h1>
        </div>
        <div class="box-body">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2>Detail</h2>
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        <dt>Tipo Alerta</dt>
                        <dd>@Model.Sto_TipoAlertas.NombreTipoAlerta(Model.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.TipoAlerta1)</dd>
                        <dt>Puntaje Minimo</dt>
                        <dd>@Model.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Min_Puntaje1</dd>
                        <dt>Puntaje Maximo</dt>
                        <dd>@Model.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Max_Puntaje1</dd>
                        <dt>Nivel Riesgo Alerta</dt>
                        <dd>@Model.Sto_NivelRiesgoAlerta.NombreNivelRiesgo(Model.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.NivelRiesgoAlerta1)</dd>
                        <dt>Accion a realizar</dt>
                        <dd>@Model.Sto_TipoAcciones.tipoAcciones.Accion1</dd>
                        <dt>Referencias</dt>
                        <dd>@Model.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.Referencias1</dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="box-footer">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlerta_NivelRiesgo/Edit.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Id_tipoAlerta_NivelRiesgo1)
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Editar</h2>
        </div>
        <div class="box-body">
            <div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Tipos Alertas", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.DropDownListFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.TipoAlerta1, Model.Sto_TipoAlertas.ListarTiposAlertasComboBox, "Todos", new { @class = "form-control" })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Puntaje Minimo", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Min_Puntaje1, new { @class = "form-control", })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Puntaje Maximo", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.Max_Puntaje1, new { @class = "form-control", })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Nivel Riesgo Alerta", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.DropDownListFor(x => x.Sto_TipoAlerta_NivelRiesgo.TipoAlerta_NivelRiesgo.NivelRiesgoAlerta1, Model.Sto_NivelRiesgoAlerta.ListaNivelRiesgoAlertaComboBox, "Todos", new { @class = "form-control" })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Accion a realizar", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.DropDownListFor(x => x.Sto_TipoAcciones.tipoAcciones.ID_Sto_TipoAcciones1, Model.Sto_TipoAcciones.ListarTipoAccionesComboBox, "-Todos-", new { @class = "form-control" })</div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">@Html.Label("Referencias", new { @class = "control-label" })</div>
                    <div class="col-md-10">@Html.TextBoxFor(x => x.Sto_Accion_TipoAlerta_NivelRiesgo.Accion_TipoAlerta.Referencias1, new { @class = "form-control" })</div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            -
            <input type="submit" value="Registrar" class="btn btn-primary" />
        </div>
    </div>
}

SeguimientoEstudiantil/SeguimientoEstudiantil/Views/TipoAlerta_NivelRiesgo/Index.cshtml
@model SeguimientoEstudiantil.Models.ModeloMaestro
@{
    ViewBag.Title = "Reglas de alertas";
}
<script>
    window.onload = function () {
        $("#vista-create").html("<i class='fa fa-spinner fa-3x fa-spin'></i>").load('@Url.Action("Create")');
        $('#tabla-reglas').DataTable();
        AOS.init({
            offset: 200,
            duration: 1000,
            easing: 'ease-out-back',
            delay: 100,
        });
    }

</script>
<script>

    hljs.initHighlightingOnLoad();

    $('.hero__scroll').on('click', function (e) {
        $('html, body').animate({
            scrollTop: $(window).height()
        }, 1200);
    });

</script>


<div class="" id="vista-create" data-aos="fade-left" data-aos-anchor="selector" data-aos-once="true"></div>

<div class="box box-primary" data-aos="fade-left" data-aos-once="true">
    <div class="box-header with-border">
        <h2 class="box-title">Listado</h2>
        <div class="box-tools pull-right">
            <!-- Buttons, labels, and many other things can be placed here! -->
            <!-- Here is a label for example -->
            <a href="@Url.Action("Detail","TipoAlerta_NivelRiesgo")" class="btn btn-default">
                <i class="fa fa-plus-circle fa-lg"></i>
            </a>
        </div>
    </div>
    <div class="box-body">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h2>Reglas de las alertas </h2>
            </div>
            <div class="panel-body">
                <table class="table table-responsive table-hover" id="tabla-reglas">
                    <thead>
                        <tr>
                            <th>Id Regla Alerta</th>
                            <th>Tipo alerta</th>
                            <th>Puntaje Minimo</th>
                            <th>Puntaje Maximo</th>
                            <th>Nivel Riesgo Alerta</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var m in Model.Sto_TipoAlerta_NivelRiesgo.ListaTipoAlerta_NivelRiesgo)
                        {
                            <tr>
                                <th>@m.Id_tipoAlerta_NivelRiesgo1</th>
                                <th>@Model.Sto_TipoAlertas.NombreTipoAlerta(m.TipoAlerta1)</th>
                                <th>@m.Min_Puntaje1</th>
                                <th>@m.Max_Puntaje1</th>
                                <th>@Model.Sto_NivelRiesgoAlerta.NombreNivelRiesgo(m.NivelRiesgoAlerta1)</th>
                                <th>
                                    <a href="@Url.Action("Detail","TipoAlerta_NivelRiesgo",new { @Id = m.Id_tipoAlerta_NivelRiesgo1 })" class="btn btn-default">
                                        <i class="fa fa-eye fa-lg"></i>
                                    </a>
                                    -
                                    <a href="@Url.Action("Edit", "TipoAlerta_NivelRiesgo", new { @Id = m.Id_tipoAlerta_NivelRiesgo1 })" class="btn btn-warning">
                                        <i class="fa fa-cog fa-lg"></i>
                                    </a>
                                    -
                                    <a href="@Url.Action("Delete", "TipoAlerta_NivelRiesgo", new { @Id = m.Id_tipoAlerta_NivelRiesgo1 })" class="btn btn-danger">
                                        <i class="fa fa-trash fa-lg"></i>
                                    </a>
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="box-footer">
        @Html.ActionLink("Regresar", "Index", "Home")
    </div>
</div>